### ISSUE TITLE
line 273, in make_output_folders_from_list     directory = output_prefix + folder TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by sirrius-black** [Senorelegans/Dogcatcher#2]
To whom it may concern: 

First, thanks for making this! I am excited to try it on my data. 

I have already run 1.0_Dogcatcher_flatten_gtf.py on Caenorhabditis_elegans.WBcel235.88.gtf

When I try to run 2.0_Dogcatcher.py on my BedGraphs I get the below error: 

Traceback (most recent call last):
  File "2.0_Dogcatcher.py", line 897, in <module>
    df = df [ df['DOG_length'] > window_size]           #PLU Get only sections where the run on length is bigger than the base window
  File "/home/wschrein/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/wschrein/anaconda2/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'DOG_length'

Here is the command that I used:

python 2.0_Dogcatcher.py  --BedGraph_input_plu_strand HS_Bedgraphs/n2_merged_control_positve.bedGraph --BedGraph_input_min_strand HS_Bedgraphs/n2_merged_control_negative.bedGraph --annotation_file_with_path gtf/Caenorhabditis_elegans.WBcel235.88.gtf --output_prefix outi --window_size 100 --coverage_percentage 90

**Comment by sagarutturkar** [comment]
I am getting a similar error with Human data. If you have any solution or workaround, your response is appreciated.

**Comment by StellamarisSoares** [comment]
I have a similar problem with the mouse data. If you have found a solution, tell me please. Thank you!
